version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: laravel10-app

    ports:
      - "8000:8000"

    volumes:
      - .:/var/www/html

    depends_on:
      - mysql

    networks:
      - laravel


  mysql:
    image: mysql:8.0

    container_name: laravel10-mysql

    restart: always

    environment:
      MYSQL_DATABASE: shop_schema
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - laravel


volumes:
  mysql_data:


networks:
  laravel: